CREATE TABLE INPUT (
	STR VARCHAR(20)
);

CREATE PROCEDURE no_args() 
BEGIN
	INSERT INTO INPUT VALUES ('no-args');
END; 

CREATE PROCEDURE in_args(a VARCHAR(5), b VARCHAR(6))
BEGIN
	INSERT INTO INPUT VALUES (CONCAT(a, b));
END ;

CREATE TABLE SRC (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	STR VARCHAR(10)
);

INSERT INTO SRC(STR) VALUES('A');
INSERT INTO SRC(STR) VALUES('B');
INSERT INTO SRC(STR) VALUES('C');
INSERT INTO SRC(STR) VALUES('D');
INSERT INTO SRC(STR) VALUES('E');

CREATE PROCEDURE GET_SRC () 
BEGIN
	SELECT * FROM SRC;
END;